all:
	bison -d especifica_11.y

	flex especifica_11.l

	gcc especifica_11.tab.c lex.yy.c -o especifica_11 -lfl

	./especifica_11 < simples.c 

	./especifica_11 < teste0.c 

	./especifica_11 < teste1.c 

	./especifica_11 < teste2.c 

	./especifica_11 < teste3.c 

	./especifica_11 < teste4.c 

	./especifica_11 < teste5.c 

	./especifica_11 < teste6.c 

	./especifica_11 < teste7.c 

	./especifica_11 < teste8.c 

	./especifica_11 < teste9.c 